resolver: lts-13.8
packages:
- .

extra-deps:
- github: pkinsky/merkle-schemes
  commit: eae760378deafc8f11031fafeb802327468c6d41
  subdirs:
    - merkle-schemes-higher
    - merkle-schemes-higher-bt
    - merkle-schemes-higher-ext
